# Generated by Django 4.2.2 on 2023-06-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Constituency",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
