# Generated by Django 4.2.2 on 2023-06-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sh_text', models.TextField(null=True)),
                ('nd_text', models.TextField(null=True)),
                ('en_text', models.TextField(null=True)),
            ],
        ),
    ]
