# Generated by Django 4.0.7 on 2022-10-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_menu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainMenu',
        ),
    ]
