# Generated by Django 4.2.2 on 2023-06-27 19:00

from django.db import migrations, models
import django.db.models.deletion
import import_export.admin


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("constituency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresidentialCandidates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=300)),
                ("political_party", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            bases=(import_export.admin.ImportExportMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MemberOfParliamentCandidates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("about", models.CharField(max_length=300)),
                ("political_party", models.CharField(max_length=50)),
                ("constituency", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="constituency.constituency",
                        verbose_name="mp_constituency",
                    ),
                ),
            ],
            bases=(import_export.admin.ImportExportMixin, models.Model),
        ),
    ]
