# Generated by Django 4.2.2 on 2023-06-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("constituency", "0001_initial"),
        ("elections_candidates", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberofparliamentcandidates",
            name="province",
        ),
        migrations.AlterField(
            model_name="memberofparliamentcandidates",
            name="constituency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="constituency.constituency",
                verbose_name="mp_constituency",
            ),
        ),
    ]
